import type { NetworkReader, NetworkRequest, ReaderNetwork } from '@repo/types';

// Offline Reader Network data (handoff Friends) — the same reader persona as the
// rest of the app. People are surfaced by books, authors and reading habits.
// All imagery is offline-safe: initials avatars + generated book-cover tones.

const REQUESTS: NetworkRequest[] = [
  {
    id: 'ri1',
    name: 'Yusuf Demirci',
    initials: 'YD',
    hue: 175,
    role: 'Literature teacher',
    mutualFriends: 6,
    mutualClubs: 2,
  },
  {
    id: 'ri2',
    name: 'Greta Lindqvist',
    initials: 'GL',
    hue: 250,
    role: 'Librarian',
    mutualFriends: 3,
    mutualClubs: 1,
  },
];

const FRIENDS: NetworkReader[] = [
  {
    id: 'mf1',
    name: 'Amara Cohen',
    initials: 'AC',
    hue: 18,
    online: true,
    role: 'Literary translator',
    country: 'Germany',
    kind: 'reading',
    score: 98,
    isFriend: true,
    book: { title: 'Beloved', author: 'Toni Morrison', tone: 2 },
    sharedBook: 'One Hundred Years of Solitude',
    mutualFriends: 12,
    mutualClubs: 3,
    sharedBooks: 23,
  },
  {
    id: 'mf2',
    name: 'Daniyar Iskakov',
    initials: 'DI',
    hue: 95,
    online: false,
    role: 'Philosophy lecturer',
    country: 'Kazakhstan',
    kind: 'literary',
    score: 92,
    isFriend: true,
    book: { title: 'Crime and Punishment', author: 'Fyodor Dostoevsky', tone: 5 },
    sharedBook: 'The Brothers Karamazov',
    mutualFriends: 8,
    mutualClubs: 2,
    sharedBooks: 17,
  },
  {
    id: 'mf3',
    name: 'Noor Haddad',
    initials: 'NH',
    hue: 158,
    online: true,
    role: 'Architecture student',
    country: 'Jordan',
    kind: 'reading',
    score: 88,
    isFriend: true,
    book: { title: 'Invisible Cities', author: 'Italo Calvino', tone: 4 },
    sharedBook: 'Invisible Cities',
    mutualFriends: 6,
    mutualClubs: 3,
    sharedBooks: 14,
  },
  {
    id: 'mf4',
    name: 'Parisa Mokri',
    initials: 'PM',
    hue: 340,
    online: true,
    role: 'Poet',
    country: 'Iran',
    kind: 'author',
    score: 81,
    isFriend: true,
    book: { title: 'The Divan of Hafez', author: 'Hafez', tone: 5 },
    sharedBook: 'The Divan of Hafez',
    mutualFriends: 15,
    mutualClubs: 4,
    sharedBooks: 9,
  },
];

const TOP_MATCHES: NetworkReader[] = [
  {
    id: 't1',
    name: 'Amara Cohen',
    initials: 'AC',
    hue: 18,
    online: true,
    role: 'Literary translator',
    country: 'Germany',
    kind: 'reading',
    score: 98,
    sharedBook: 'One Hundred Years of Solitude',
    basis: ['Favourite books', 'Reading habits', '3 shared clubs'],
    book: { title: 'Beloved', author: 'Toni Morrison', tone: 2 },
    mutualFriends: 12,
    mutualClubs: 3,
    sharedBooks: 23,
  },
  {
    id: 't2',
    name: 'Daniyar Iskakov',
    initials: 'DI',
    hue: 95,
    online: false,
    role: 'Philosophy lecturer',
    country: 'Kazakhstan',
    kind: 'literary',
    score: 92,
    sharedBook: 'The Brothers Karamazov',
    basis: ['Academic interests', 'Genres', 'Favourite authors'],
    book: { title: 'Crime and Punishment', author: 'Fyodor Dostoevsky', tone: 5 },
    mutualFriends: 8,
    mutualClubs: 2,
    sharedBooks: 17,
  },
  {
    id: 't3',
    name: 'Lina Soltani',
    initials: 'LS',
    hue: 300,
    online: true,
    role: 'MFA candidate',
    country: 'Iran',
    kind: 'author',
    score: 85,
    sharedBook: 'Kafka on the Shore',
    basis: ['Favourite authors', 'Reading goals'],
    book: { title: '1Q84', author: 'Haruki Murakami', tone: 1 },
    mutualFriends: 5,
    mutualClubs: 2,
  },
];

const MAY_KNOW: NetworkReader[] = [
  {
    id: 'k1',
    name: 'Theo Almeida',
    initials: 'TA',
    hue: 210,
    online: false,
    role: 'Bookseller',
    country: 'Portugal',
    kind: 'reading',
    score: 91,
    book: { title: 'The Name of the Rose', author: 'Umberto Eco', tone: 5 },
    mutualFriends: 7,
    mutualClubs: 2,
  },
  {
    id: 'k2',
    name: 'Noor Haddad',
    initials: 'NH',
    hue: 158,
    online: true,
    role: 'Architecture student',
    country: 'Jordan',
    kind: 'literary',
    score: 88,
    book: { title: 'Invisible Cities', author: 'Italo Calvino', tone: 4 },
    mutualFriends: 4,
    mutualClubs: 3,
  },
  {
    id: 'k3',
    name: 'Mateo Rossi',
    initials: 'MR',
    hue: 18,
    online: false,
    role: 'PhD · Comparative Lit',
    country: 'Italy',
    kind: 'author',
    score: 84,
    book: { title: "If on a winter's night a traveler", author: 'Italo Calvino', tone: 1 },
    mutualFriends: 9,
    mutualClubs: 1,
  },
];

const UNIVERSITY: NetworkReader[] = [
  {
    id: 'u1',
    name: 'Roya Tehrani',
    initials: 'RT',
    hue: 158,
    online: true,
    role: 'Student · Literature',
    university: 'Student · Literature',
    kind: 'literary',
    score: 86,
    book: { title: 'The Blind Owl', author: 'Sadegh Hedayat', tone: 1 },
  },
  {
    id: 'u2',
    name: 'Kaveh Bahrami',
    initials: 'KB',
    hue: 210,
    online: false,
    role: 'Alumnus · Philosophy',
    university: 'Alumnus · Philosophy',
    kind: 'author',
    score: 79,
    book: { title: 'Being and Time', author: 'Martin Heidegger', tone: 6 },
  },
  {
    id: 'u3',
    name: 'Omid Nasseri',
    initials: 'ON',
    hue: 95,
    online: true,
    role: 'Student · Persian Lit',
    university: 'Student · Persian Lit',
    kind: 'reading',
    score: 90,
    book: { title: 'The Conference of the Birds', author: 'Attar', tone: 5 },
  },
];

export const READER_NETWORK: ReaderNetwork = {
  requests: REQUESTS,
  friends: FRIENDS,
  mayKnow: MAY_KNOW,
  topMatches: TOP_MATCHES,
  university: UNIVERSITY,
};
