import type { ClubsDirectory } from '@repo/types';

// Offline Clubs directory (handoff §6.5). Counts are raw numbers; the UI formats
// them with @repo/utils formatCompactNumber. Swap the mock client for the real
// one and this file goes away.
export const CLUBS_DIRECTORY: ClubsDirectory = {
  myClubs: [
    {
      id: 'f1',
      name: 'The Midnight Library Club',
      logo: 'ML',
      members: 48200,
      tone: 2,
      icon: 'book',
      activity: 'buzzing',
    },
    {
      id: 'f2',
      name: 'Fantasy Realms',
      logo: 'FR',
      members: 126400,
      tone: 3,
      icon: 'wand',
      activity: 'high',
    },
    {
      id: 'f3',
      name: 'Mystery & Mayhem',
      logo: 'MM',
      members: 73900,
      tone: 1,
      icon: 'masks',
      activity: 'high',
    },
    {
      id: 'f4',
      name: 'Translated Fiction Society',
      logo: 'TF',
      members: 31500,
      tone: 4,
      icon: 'globe',
      activity: 'medium',
    },
  ],
  publishers: [
    {
      id: 'p1',
      name: 'Oxford University Press Readers',
      logo: 'OUP',
      followers: 64800,
      tone: 2,
      icon: 'gradCap',
    },
    {
      id: 'p2',
      name: 'Goethe Publishing Community',
      logo: 'GP',
      followers: 28300,
      tone: 5,
      icon: 'feather',
    },
    {
      id: 'p3',
      name: 'Penguin Books Community',
      logo: 'PB',
      followers: 218400,
      tone: 0,
      icon: 'book',
    },
    {
      id: 'p4',
      name: 'HarperCollins Readers',
      logo: 'HC',
      followers: 132900,
      tone: 1,
      icon: 'book',
    },
    {
      id: 'p5',
      name: 'Simon & Schuster Community',
      logo: 'S&S',
      followers: 97600,
      tone: 3,
      icon: 'book',
    },
    { id: 'p6', name: 'Macmillan Readers', logo: 'MR', followers: 71200, tone: 6, icon: 'book' },
  ],
  series: [
    {
      id: 's1',
      name: 'Harry Potter Fans',
      logo: 'HP',
      members: 312000,
      tone: 3,
      icon: 'wand',
      activity: 'buzzing',
    },
    {
      id: 's2',
      name: 'The Lord of the Rings Community',
      logo: 'LR',
      members: 184500,
      tone: 0,
      icon: 'globe',
      activity: 'high',
    },
    {
      id: 's3',
      name: 'A Song of Ice and Fire Readers',
      logo: 'IF',
      members: 142800,
      tone: 1,
      icon: 'book',
      activity: 'high',
    },
    {
      id: 's4',
      name: 'Percy Jackson Club',
      logo: 'PJ',
      members: 96300,
      tone: 4,
      icon: 'sparkles',
      activity: 'high',
    },
    {
      id: 's5',
      name: 'Sherlock Holmes Readers',
      logo: 'SH',
      members: 71200,
      tone: 6,
      icon: 'masks',
      activity: 'medium',
    },
    {
      id: 's6',
      name: 'Narnia Readers',
      logo: 'NR',
      members: 58400,
      tone: 5,
      icon: 'wand',
      activity: 'medium',
    },
  ],
  adaptations: [
    {
      id: 'a1',
      name: 'Dune Community',
      book: 'Dune',
      author: 'Frank Herbert',
      screen: 'Film · 2021',
      members: 88700,
      bookTone: 5,
    },
    {
      id: 'a2',
      name: 'The Hunger Games',
      book: 'The Hunger Games',
      author: 'Suzanne Collins',
      screen: 'Film series',
      members: 134200,
      bookTone: 1,
    },
    {
      id: 'a3',
      name: 'The Witcher Readers',
      book: 'The Last Wish',
      author: 'Andrzej Sapkowski',
      screen: 'TV · Netflix',
      members: 102600,
      bookTone: 0,
    },
    {
      id: 'a4',
      name: 'The Maze Runner',
      book: 'The Maze Runner',
      author: 'James Dashner',
      screen: 'Film series',
      members: 47300,
      bookTone: 4,
    },
    {
      id: 'a5',
      name: 'Shadow and Bone',
      book: 'Shadow and Bone',
      author: 'Leigh Bardugo',
      screen: 'TV · Netflix',
      members: 65100,
      bookTone: 3,
    },
    {
      id: 'a6',
      name: 'The Fault in Our Stars',
      book: 'The Fault in Our Stars',
      author: 'John Green',
      screen: 'Film · 2014',
      members: 53800,
      bookTone: 2,
    },
  ],
  authors: [
    {
      id: 'au1',
      name: 'J.K. Rowling Readers',
      initials: 'JR',
      hue: 300,
      members: 287000,
      books: 14,
    },
    { id: 'au2', name: 'J.R.R. Tolkien Fans', initials: 'JT', hue: 95, members: 173400, books: 18 },
    {
      id: 'au3',
      name: 'George R.R. Martin Community',
      initials: 'GM',
      hue: 18,
      members: 138900,
      books: 12,
    },
    {
      id: 'au4',
      name: 'Agatha Christie Readers',
      initials: 'AC',
      hue: 268,
      members: 112600,
      books: 66,
    },
    {
      id: 'au5',
      name: 'Stephen King Community',
      initials: 'SK',
      hue: 12,
      members: 204300,
      books: 64,
    },
    {
      id: 'au6',
      name: 'Haruki Murakami Readers',
      initials: 'HM',
      hue: 210,
      members: 96800,
      books: 22,
    },
  ],
};
